name: Fetch all models from gsmarena

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: devices-${{ github.ref }}
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Checkout databases
      uses: actions/checkout@v3
      with:
        ref: 'refs/heads/db'
        path: 'db'

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '17'
       cache: 'maven'

    - name: Build bot
      run: |
        mvn package

    - name: Run bot
      env:
       BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        java -jar target/SamsungFirmwareBot.jar scrapeDevices

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        path: devices.txt

    - name: Update devices
      run: |
        git -C db config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git -C db config --local user.name "github-actions[bot]"
        git -C db pull origin db --ff-only
        git -C db add devices.db
        git -C db commit -m "samsungfwbot: Devices list update $(date)" || true

    - name: Push database changes to repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'db'
        directory: 'db'
